name: Label pull request

on:
  pull_request_target:
    branches:
      - "*"
    types:
      - opened

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GH_BOT_TOKEN }}
          configuration-path: .github/labeler.yaml
